name: github2dropbox
description: "Backup GitHub Data to DropBox"
inputs:
  GITHUB_TOKEN:
    description: "Access Token to GitHub"
    required: true
  DROPBOX_TOKEN:
    description: "Access Token to Dropbox"
    required: true
  DROPBOX_PATH:
    description: "With Path To Store With Dropbox"
    required: false
  ENABLE_REPO:
    description: "Enable Repo Backup"
    required: false
  ENABLE_REPO_GIT:
    description: "Enable Repo Git Backup"
    required: false
  ENABLE_STAR:
    description: "Enable Star Backup"
    required: false
  ENABLE_FOLLOWER:
    description: "Enable Follower Backup"
    required: false
  ENABLE_FOLLOWING:
    description: "Enable Following Backup"
    required: false
  ENABLE_GIST:
    description: "Enable Gist Backup"
    required: false
  ENABLE_ISSUE:
    description: "Enable Issue Backup"
    required: false
  ENABLE_ISSUE_COMMENT:
    description: "Enable Issue Comment Backup"
    required: false
runs:
  using: docker
  image: Dockerfile
